### ISSUE TITLE
Question About Ensuring Purity of pcap Dataset

### ISSUE THREAD

**Issue by bigbigbighead** [ErnestThePoet/EncryptedTrafficClassification#1]
Hello,I’ve been using Wireshark to capture packets and save them as pcap files, but I keep running into the issue of extra traffic getting mixed in. How do you ensure that the datasets you collected sorely from a specific application rather than some background system processes ? Any tips or tools you recommend for filtering out the noise?Thanks in advance.

**Comment by ErnestThePoet** [comment]
Actually Wireshark is not capable of filtering packets by application. To work around this, we could find and use patterns from specific application traffic. For instance, we observe that QQ sends most UDP packets to IP `a.b.c.d`, so we filter `ip.addr == a.b.c.d` in Wireshark, resulting in packets mostly from QQ; for HTTPS, we filter with `tcp.port == 443`, etc.

**Comment by bigbigbighead** [comment]
OK I got it.Thanks a lot!
